### ISSUE TITLE
Use Executioner Time Instead

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#20]
I just realised that using `serverTime()` in the executioner result is unstable because sometimes `testing` happens after `tested` if the run is really fast. Can we use client time (the executioner) instead which is synced when the executioner starts up. It's not really affecting anything now because the frontend would just ignore `testing` when it sees `tested`.

**Comment by Daniel5055** [comment]
Oh that's interesting. I encountered a problem a while ago where all the testing messages would be sent before the tested messages as everything was handled asynchronously. As checking the results would generally take longer, the testing messages resolved and sent before the tested messages did, hence the issue.

But this was fixed by messages requiring the previous message to already resolve before sending the next and I haven't had an issue since. 

This does mean however that the time between messages is very small and could be what is causing the issue with ServerTime then

**Comment by DE0CH** [comment]
I see. I guess one thing you can try to do is to note down the time at a predictable and in order place and then handle everything afterward asynchronously.

**Comment by DE0CH** [comment]
Not sure why this is happening again. @Daniel5055 Can you look at it again? Btw it was running commit 768266e
![](https://cdn.discordapp.com/attachments/965976708186533930/1013811876909568100/unknown.png)

**Comment by Daniel5055** [comment]
The executioner now awaits for state updates and judge result additions for a message before sending the next message. I've also reverted back to using servertime now as that seems more fitting. This should fix the issue as it prevents race conditions yet this is quite hard to test.
