### ISSUE TITLE
Code Injection?

### ISSUE THREAD

**Issue by DE0CH** [CP-STA/STAOJ#44]
The following js code causes all test cases to be evaluated as TLE. 

```javascript
console.err("Out of time!")
```

I can't think of a reason why someone would deliberately sabotage their own submission. But would this cause any problem?

**Comment by Daniel5055** [comment]
That's fun. This is because the demoter and code streams are the same. Demoter will print usage to stdout and that will always be the last two lines so nothing to worry there. In stderr it's a bit more jumbled. Demoter and program both write to stderr. All the executioner does is look for either the MLE or TLE statement in the error file to deduce the error if there was an error.

There are 2 solutions I can immediately think of. 

1 is to have the demoter write its deduction (TLE or MLE) to another file. But this only partly solves the problem as the script afterwards will try to read the errors logged by the program to deduce if it was a memory limit error. E.g std:bad_alloc in C++. This is because programs will always crash with some error if they run out of memory and I've found that checking how close mem usage was to mem limit to be quite inconsistent.

2 is to keep error deductions in the shared stderr but prefix them with a unique identifier. Either the submission uuid or a new one agreed upon by demoter and executioner. The reason I mention two options here is because I don't think the program can ever read it's own uuid on runtime but I'm not 100% sure. Therefore, this would completely prevent the program from spoofing bad MLE or TLE.

**Comment by DE0CH** [comment]
This should mitigate it. I just make sure that the last line of stderr is from the demoter, and only read the last line. 

But for some reason the demoter does not capture the stderr from the program. Think that issue is for another day.

**Comment by DE0CH** [comment]
Actually the bug is super weird. `console.err` is not even a function, and when I tried to use `console.error`, the bug disappeared. 

I guess it somehow captured the traceback from nodejs but not actually anything the user outputted to stderr?
